// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:package': typeof import('virtual:vite-icons/carbon/package')['default']
    Expand: typeof import('./src/components/expand.vue')['default']
    'Gg:browser': typeof import('virtual:vite-icons/gg/browser')['default']
    'Ic:baselineCheck': typeof import('virtual:vite-icons/ic/baseline-check')['default']
    'Ic:roundBolt': typeof import('virtual:vite-icons/ic/round-bolt')['default']
    'Ic:roundClose': typeof import('virtual:vite-icons/ic/round-close')['default']
    'Ic:sharpShare': typeof import('virtual:vite-icons/ic/sharp-share')['default']
    LogosJavascript: typeof import('virtual:vite-icons/logos/javascript')['default']
    LogosTypescriptIcon: typeof import('virtual:vite-icons/logos/typescript-icon')['default']
    LogosVue: typeof import('virtual:vite-icons/logos/vue')['default']
    'Mdi:loading': typeof import('virtual:vite-icons/mdi/loading')['default']
    'Mdi:packageVariantClosed': typeof import('virtual:vite-icons/mdi/package-variant-closed')['default']
    Monaco: typeof import('./src/components/monaco/monaco.vue')['default']
    Packges: typeof import('./src/components/packages/packges.vue')['default']
    'Ph:trash': typeof import('virtual:vite-icons/ph/trash')['default']
    'Ri:installLine': typeof import('virtual:vite-icons/ri/install-line')['default']
    Sandbox: typeof import('./src/components/iframe/sandbox.vue')['default']
    'VscodeIcons:fileTypeLightJson': typeof import('virtual:vite-icons/vscode-icons/file-type-light-json')['default']
  }
}

export { }
