// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Ic:roundClose': typeof import('virtual:vite-icons/ic/round-close')['default']
    'Ic:roundSettings': typeof import('virtual:vite-icons/ic/round-settings')['default']
    LogosJavascript: typeof import('virtual:vite-icons/logos/javascript')['default']
    LogosTypescriptIcon: typeof import('virtual:vite-icons/logos/typescript-icon')['default']
    LogosVue: typeof import('virtual:vite-icons/logos/vue')['default']
    'Mdi:packageVariantClosed': typeof import('virtual:vite-icons/mdi/package-variant-closed')['default']
    Monaco: typeof import('./src/components/monaco/monaco.vue')['default']
    Packges: typeof import('./src/components/packages/packges.vue')['default']
    'Ri:installLine': typeof import('virtual:vite-icons/ri/install-line')['default']
    Sandbox: typeof import('./src/components/iframe/sandbox.vue')['default']
    View: typeof import('./src/components/dialog/view.vue')['default']
    'VscodeIcons:fileTypeLightJson': typeof import('virtual:vite-icons/vscode-icons/file-type-light-json')['default']
  }
}

export { }
