// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Ic:roundClose': typeof import('virtual:vite-icons/ic/round-close')['default']
    LogosJavascript: typeof import('virtual:vite-icons/logos/javascript')['default']
    LogosTypescriptIcon: typeof import('virtual:vite-icons/logos/typescript-icon')['default']
    LogosVue: typeof import('virtual:vite-icons/logos/vue')['default']
    Monaco: typeof import('./src/components/monaco/monaco.vue')['default']
    Sandbox: typeof import('./src/components/iframe/sandbox.vue')['default']
    'VscodeIcons:fileTypeLightJson': typeof import('virtual:vite-icons/vscode-icons/file-type-light-json')['default']
  }
}

export { }
