name: Deploy Github Packages

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'poyoho/playground'
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install deps
        run: pnpm ci

      - name: Build
        run: pnpm build

      - name: Deploy
        run: pnpm run ci-deploy

